apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: projected-resource-secret-configmap-share-watch-sar-create
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - projectedresource.storage.openshift.io
    resources:
      - shares
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create